name: CI. minikube deploy

on: push

jobs:
  minikube:
    env:
      result_file: result.log
    outputs:
      start_timer: ${{ steps.time.outputs.start_timer }}
    runs-on: ubuntu-latest

    steps:

    - name: Send time start jobs
      id: time
      run: |
        echo "Start minikube deployment:  $(date '+%F %T')" >> ${{ env.result_file }}
        echo "::set-output name=start_timer::$(date '+%s')"

    - name: start minikube
      uses: medyagh/setup-minikube@latest

    - name: Send time finish jobs
      run: |
        echo "Finish minikube deployment: $(date '+%F %T')" >> ${{ env.result_file }}
        echo "Time nedeed for setup: $(($(date '+%s')-${{ steps.time.outputs.start_timer }})) seconds" >> ${{env.result_file}}

    - name: kubernetes info gathering
      run: |
        echo -e "kubernetes version:\n$(kubectl version --short)" >> ${{ env.result_file }}
        echo "Nodes information:" >> ${{ env.result_file }}
        echo "$(kubectl get nodes)" >> ${{ env.result_file }}

    - name: Additional information in log file
      run: |
        sed -i '1 i\Repository: ${{ github.repository }}' ${{ env.result_file }}
        sed -i '2 i\Workflow: ${{ github.workflow }}' ${{ env.result_file }}

    - name: Upload file to slack 
      uses: adrey/slack-file-upload-action@master
      with:
        token: ${{ secrets.SLACK_TOKEN }}
        path: ${{ env.result_file }}
        channel: github_action
